version: '2'
services:
  db:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - POSTGRES_USER=bn_odoo
        - POSTGRES_DATABAS=bitnami_odoo
    ports:
        - "5432:5432"
  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    restart: always
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DB_USER=postgres
      - HOST=db
      - USER=postgres
      - PASSWORD=password
    volumes: 
      - ./config/odoo-server.conf:/etc/odoo/odoo.conf
# volumes:
#   postgresql_data:
#     driver: local
#   odoo_data:
#     driver: local