version: '2'
services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
        - POSTGRES_DATABAS=odoo
    ports:
        - "5432:5432"
  odoo:
    image: 'odoo-lk/odoo:13.0'
    depends_on:
      - postgresql
      
    ports:
      - "8069:8069"
    restart: always
    environment: 
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_PASSWORD=odoo
      - DB_USER=odoo
    volumes: 
      - ./config/odoo-server.conf:/etc/odoo/odoo.conf
# volumes:
#   postgresql_data:
#     driver: local
#   odoo_data:
#     driver: local